### ISSUE TITLE
ogon can not be build with `cmake -GNinja`

### ISSUE THREAD

**Issue by akallabeth** [ogon-project/ogon-project#7] opened 2019-09-16 07:46 UTC
`
ninja: error: 'external/Install/thrift/lib/libthrift.a', needed by 'session-manager/ogon-session-manager', missing and no known rule to make it
`

**Comment by bmiklautz** [comment] 2019-09-18 07:25
@akallabeth when thrift is used as external project we did only test with Makefile. The problem is that thirft (as included) can't be built in parallel.

**Comment by bmiklautz** [comment] 2020-10-30 09:19
@akallabeth with thrift updated this should work now. Would you give it a re-try?

**Comment by hardening** [comment] 2020-10-30 09:23
@bmiklautz we can close it it works perfectly now

**Closed as completed** 2020-10-30 09:23 UTC
Labels: waiting-for-feedback, core
